# Generated by Django 5.2.12 on 2026-04-07 13:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(max_length=50)),
                ('overall_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('fatigue_index', models.FloatField(default=0.0)),
                ('most_frequent_error', models.CharField(blank=True, max_length=255, null=True)),
                ('accuracy_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('best_set', models.IntegerField(default=1)),
                ('worst_set', models.IntegerField(default=1)),
                ('total_reps', models.IntegerField(default=0)),
                ('session_deviation', models.FloatField(default=0.0)),
                ('total_sets', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SessionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('set_number', models.IntegerField()),
                ('raw_report_json', models.TextField()),
                ('normalized_accuracy', models.FloatField(default=0.0)),
                ('normalized_deviation', models.FloatField(default=0.0)),
                ('normalized_stability', models.FloatField(default=0.0)),
                ('normalized_range_of_motion', models.FloatField(default=0.0)),
                ('normalized_rep_validity', models.FloatField(default=0.0)),
                ('set_score', models.FloatField(default=0.0)),
                ('total_errors', models.IntegerField(default=0)),
                ('rep_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='stream_video.session')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('session', 'set_number')},
            },
        ),
    ]
